name: untitled
description: "A new Flutter project with Firebase authentication."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.15.0
  firebase_auth: ^4.10.0

  # UI & Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
